# Generated by Django 6.0.7 on 2026-07-30 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=255, verbose_name='Auteur')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('nombre_exemplaires', models.PositiveIntegerField(default=1, verbose_name="Nombre d'exemplaires")),
                ('nombre_exemplaires_disponibles', models.PositiveIntegerField(default=1, verbose_name='Exemplaires disponibles')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('date_retour_prevue', models.DateField(verbose_name='Date de retour prévue')),
                ('date_retour_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour réelle')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retourne', 'Retourné'), ('en_retard', 'En retard')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.livre', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
    ]
