# Generated by Django 6.0.7 on 2026-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lecteur', 'Lecteur'), ('bibliothecaire', 'Bibliothécaire')], default='lecteur', max_length=20, verbose_name='Rôle'),
        ),
    ]
